### PR TITLE
Setup gradle

### PR DESCRIPTION
**Pull request by Dhina17**

### CODE REVIEW

**Comment by Dhina17** [comment]
@XomaDev Please let me what's the problem with the DeepSource check

**Comment by XomaDev** [comment]
Thanks for the PR 🙂
It works perfectly, it generates the classes.jar successfully.

The DeepSource servers are down right now, so we need to wait to check whats wrong.
However, I dont think its a big problem and we can safely ignore it.

**Comment by Dhina17** [comment]
Yes I tested it with jitpack. I will add a test app module later.

**Comment by XomaDev** [comment]
Thanks for the contribution.

**Review by lwyytakeru — APPROVED** [review]

**Pull request merged**
