### PR TITLE
Add an app module for example

### PR DESCRIPTION
**Pull request by Dhina17**

### CODE REVIEW

**Comment by Dhina17** [comment]
@XomaDev Shall I know why it's not merged yet?

**Comment by XomaDev** [comment]
I'll do it soon, I had other projects and exams.

**Comment by XomaDev** [comment]
I just wanted to tell you that the previous Gradle PR, does not include the other library required for the Autostart class (gradle output, misses it).
I.e, `me.weishu.reflection.Reflection`, this should be fixed first ASAP.

Therefore the library does not function anymore when the `classes.jar` is directly used.

**Comment by Dhina17** [comment]
> I just wanted to tell you that the previous Gradle PR, does not include the other library required for the Autostart class (gradle output, misses it). I.e, `me.weishu.reflection.Reflection`, this should be fixed first ASAP.
> 
> Therefore the library does not function anymore when the `classes.jar` is directly used.

https://github.com/XomaDev/MIUI-autostart/blob/fda33ab5d32ffe526d8449c8a7ffaa91e10a32d0/library/build.gradle#L32

It included correctly

**Comment by XomaDev** [comment]
Yes, but not in the `/library/build/intermediates/compile_library_classes_jar/...`.
I think we can ignore it, since it would be solved if one uses the Autostart library through gradle.

**Comment by Dhina17** [comment]
I hope no one gonna use it without gradle since it's an android specific project.
We can ignore it.

**Comment by XomaDev** [comment]
Alright. Will check the PR today,
(Update: this may take longer, I just moved stuff to a new computer)

**Comment by XomaDev** [comment]
Looks good, thanks for the PR.

**Pull request merged**
